In [16]:
import numpy as np

np.__version__


'1.18.5'

In [6]:
arr = numpy.array([i for i in range(10000)])

arr

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [6]:
import array

```py
array.array('i', [i for i in range(10)])
```

'i': 这里指的是 int

In [11]:
arr = array.array('i', [i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr[5]

5

In [15]:
arr[3] = 'abc'

TypeError: an integer is required (got type str)

## numpy.array

它会有个默认转换


In [18]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
nparr[5] = 'hello'

ValueError: invalid literal for int() with base 10: 'hello'

In [22]:
nparr.dtype

dtype('int64')

In [25]:
nparr[4] = 4.345

In [24]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
nparr2 = np.array([1, 2, 3.0])

In [28]:
nparr2.dtype

dtype('float64')

## 其他创建numpy.array 的方法

3行5列矩阵
numpy.zeros((3, 5))

numpy.zeros(shape=(3, 5), dtype=int)

numpy.full(shape=(3, 5), fill_value=666)

In [29]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
np.zeros(10).dtype

dtype('float64')

In [31]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
 np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
np.zeros(shape=(3, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [34]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
np.full(shape=(3, 5), fill_value=666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

## arange


In [37]:
[i for i in range(0, 10, 2)]

[0, 2, 4, 6, 8]

In [39]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

## linspace

在 [0, 20] 这个范围内，分割5份
np.linspace(0, 20, 5)


In [41]:
np.linspace(0, 20, 5)

array([ 0.,  5., 10., 15., 20.])

## random

生成随机数

随机数种子，指定一样的话，下次生成是一样的
np.random.seed(666)

正态分布
np.random.normal(0, 1, (3, 5))


In [42]:
np.random.randint(0, 10)

3

In [45]:
np.random.randint(0, 10, 5)

array([6, 4, 1, 6, 5])

In [46]:
np.random.randint(0, 1, 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [49]:
np.random.randint(0, 10, size=(3, 5))

array([[7, 5, 2, 1, 3],
       [8, 9, 9, 4, 3],
       [9, 3, 7, 9, 1]])

In [50]:
np.random.seed(666)

In [51]:
np.random.randint(0, 10, size=(3, 5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

In [53]:
np.random.seed(666)
np.random.randint(0, 10, size=(3, 5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

In [54]:
np.random.randint(0, 10, size=(3, 5))

array([[4, 4, 0, 0, 4],
       [0, 4, 5, 7, 1],
       [0, 0, 6, 6, 0]])

In [55]:
np.random.random()

0.8888993137763092

In [56]:
np.random.random(10)

array([0.62640453, 0.81887369, 0.54734542, 0.41671201, 0.74304719,
       0.36959638, 0.07516654, 0.77519298, 0.21940924, 0.07934213])

In [57]:
np.random.random((3, 5))

array([[0.48678052, 0.1536739 , 0.82846513, 0.19136857, 0.27040895],
       [0.56103442, 0.90238039, 0.85178834, 0.41808196, 0.39347627],
       [0.01622051, 0.29921337, 0.35377822, 0.89350267, 0.78613657]])

In [62]:
np.random.normal()

1.518145140043964

In [63]:
np.random.normal(10, 100)

17.722188275491053

In [64]:
np.random.normal(0, 1, (3, 5))

array([[-0.06399132,  0.94592341,  1.20409101, -0.45124074, -1.58744651],
       [-1.86885548,  0.10037737, -3.09487059,  3.39351678, -0.12666878],
       [-0.93713026,  0.56552529,  0.3158975 , -0.79572225,  0.50507572]])

In [67]:
np.random.normal?

In [68]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of numpy.random.mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    .. note::
        New code should use the ``normal`` method of a ``default_rng()``
        instance instead; see `random-quick-start`.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : fl

### numpy.arange 基本属性

ndim: 几维数组

shape: 每个维度上有几个元素

size: 元素个数

In [70]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
X = np.arange(15).reshape(3, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [72]:
x.ndim

1

In [73]:
X.ndim

2

In [74]:
x.shape

(10,)

In [75]:
X.shape

(3, 5)

In [76]:
x.size

10

In [77]:
X.size

15

In [79]:
X[0][0]

0

In [80]:
X[2, 2]

12

In [92]:
x[:2]

array([0, 1])

In [84]:
x[0:5]

array([0, 1, 2, 3, 4])

In [85]:
x[::2]

array([0, 2, 4, 6, 8])

In [82]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [86]:
x[::-2]

array([9, 7, 5, 3, 1])

In [87]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [88]:
X[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [91]:
X[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [90]:
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [93]:
X[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [94]:
X[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [95]:
X[:, 0]

array([ 0,  5, 10])

In [96]:
X[:, 0].ndim

1

In [99]:
subX = X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [100]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [101]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [102]:
X[0, 0] = 0
X
subX

array([[0, 1, 2],
       [5, 6, 7]])

> 注意 子数组修改会影响父数组， 不想修改的话用copy()

In [103]:
subX = X[:2, :3].copy()
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [106]:
subX[0][0] = 100
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### reshape

In [113]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
x.ndim

1

In [115]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [116]:
A = x.reshape(2, 5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [117]:
A.shape

(2, 5)

In [109]:
B = x.reshape(1, 10)
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [112]:
B.shape

(1, 10)

In [118]:
x.reshape(10, -1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [119]:
x.reshape(-1, 10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [120]:
x.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [121]:
x.reshape(3, -1)

ValueError: cannot reshape array of size 10 into shape (3,newaxis)